# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300)),
                ('picture', models.CharField(max_length=30)),
                ('checked', models.BooleanField(choices=[(0, '否'), (1, '是')], max_length=1)),
            ],
        ),
    ]
