# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=63)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.TimeField()),
                ('title', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('content', models.CharField(max_length=256)),
                ('favor_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('ctime', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.NewsType'),
        ),
        migrations.AddField(
            model_name='news',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='favor',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.News'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
    ]
